# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestingProject' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

      # Pods for VoximplantDemo
      pod 'React', :path => '../node_modules/react-native', :subspecs => [
      'Core',
      'CxxBridge',
      'RCTNetwork',
      'RCTText',
      'RCTWebSocket',
      'DevSupport',
      'RCTLinkingIOS',
    
      # Add any other subspecs you want to use in your project
      ]

      # Demo project dependencies
      pod 'react-native-voximplant', path: '../../react-native-voximplant.podspec'


      pod 'Jet', :path => '../node_modules/jet/ios/Jet.podspec'
      # Explicitly include Yoga if you are using RN >= 0.42.0
      pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

      # Third party deps podspec link
      pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
      pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/GLog.podspec'
      pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

      post_install do |installer|
          installer.pods_project.targets.each do |target|
              target.build_configurations.each do |config|
                  config.build_settings['ENABLE_BITCODE'] = 'NO'
              end
          end
      end

      target 'TestingProjectTests' do
      	inherit! :search_paths
      end

end
